-- Crear indices de auditoria si no existen
CREATE INDEX IF NOT EXISTS "idx_audits_user_id" ON "ff_medic_db"."audits"("user_id");
CREATE INDEX IF NOT EXISTS "idx_audits_table_record" ON "ff_medic_db"."audits"("table_name", "record_id");

-- Agregar comentarios a tablas
COMMENT ON TABLE ff_medic_db.patients IS 'Pacientes del consultorio';
COMMENT ON TABLE ff_medic_db.roles IS 'Roles del sistema';
COMMENT ON TABLE ff_medic_db.users IS 'Usuarios del sistema';
COMMENT ON TABLE ff_medic_db.services IS 'Servicios del consultorio';
COMMENT ON TABLE ff_medic_db.diagnoses IS 'Diagnósticos CIE-10';
COMMENT ON TABLE ff_medic_db.active_ingredients IS 'Principios activos de medicamentos';
COMMENT ON TABLE ff_medic_db.manufacturers IS 'Fabricantes de medicamentos';
COMMENT ON TABLE ff_medic_db.dosage_forms IS 'Formas farmacéuticas de medicamentos';
COMMENT ON TABLE ff_medic_db.medicaments IS 'Medicamentos del consultorio';
COMMENT ON TABLE ff_medic_db.medicaments_ingredients IS 'Relación N:M entre medicamentos y principios activos';
COMMENT ON TABLE ff_medic_db.attentions IS 'Atenciones médicas';
COMMENT ON TABLE ff_medic_db.attention_diagnoses IS 'Diagnósticos asociados a la atención';
COMMENT ON TABLE ff_medic_db.signs_symptoms IS 'Signos y síntomas de la atención';
COMMENT ON TABLE ff_medic_db.health_metrics IS 'Métricas de salud de la atención (signos vitales, peso, talla, perímetro abdominal, HGT, hemoglobina)';
COMMENT ON TABLE ff_medic_db.bio_functions IS 'Funciones biológicas de la atención';
COMMENT ON TABLE ff_medic_db.physical_exams IS 'Sistemas evaluados en el examen físico';
COMMENT ON TABLE ff_medic_db.exams IS 'Órdenes de examen de la atención';
COMMENT ON TABLE ff_medic_db.exam_types IS 'Tipos de examen auxiliar';
COMMENT ON TABLE ff_medic_db.exam_items IS 'Ítems de la orden de examen';
COMMENT ON TABLE ff_medic_db.prescriptions IS 'Recetas médicas de la atención';
COMMENT ON TABLE ff_medic_db.prescription_items IS 'Medicamentos de la receta';
COMMENT ON TABLE ff_medic_db.prescription_diagnoses IS 'Diagnósticos asociados al medicamento recetado';
COMMENT ON TABLE ff_medic_db.referrals IS 'Interconsultas de la atención';
COMMENT ON TABLE ff_medic_db.clinical_histories IS 'Antecedentes patológicos y quirúrgicos del paciente';
COMMENT ON TABLE ff_medic_db.family_histories IS 'Antecedentes familiares del paciente';
COMMENT ON TABLE ff_medic_db.gynecological_histories IS 'Antecedentes ginecológicos del paciente';
COMMENT ON TABLE ff_medic_db.allergy_histories IS 'Antecedentes de alergias del paciente';
COMMENT ON TABLE ff_medic_db.ram_histories IS 'Reacciones Adversas a Medicamentos del paciente';
COMMENT ON TABLE ff_medic_db.audits IS 'Auditoría de acciones del sistema';

-- Agregar comentarios a columnas
COMMENT ON COLUMN ff_medic_db.patients.patient_id IS 'Identificador único del paciente';
COMMENT ON COLUMN ff_medic_db.patients.document_type IS 'Tipo de documento del paciente';
COMMENT ON COLUMN ff_medic_db.patients.document_number IS 'Número de documento del paciente';
COMMENT ON COLUMN ff_medic_db.patients.name IS 'Nombre del paciente';
COMMENT ON COLUMN ff_medic_db.patients.paternal_surname IS 'Apellido paterno del paciente';
COMMENT ON COLUMN ff_medic_db.patients.maternal_surname IS 'Apellido materno del paciente';
COMMENT ON COLUMN ff_medic_db.patients.sex IS 'Sexo del paciente';
COMMENT ON COLUMN ff_medic_db.patients.phone IS 'Teléfono del paciente';
COMMENT ON COLUMN ff_medic_db.patients.birth_date IS 'Fecha de nacimiento del paciente';
COMMENT ON COLUMN ff_medic_db.patients.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.patients.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.patients.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.roles.role_id IS 'Identificador único del rol';
COMMENT ON COLUMN ff_medic_db.roles.name IS 'Nombre del rol';
COMMENT ON COLUMN ff_medic_db.roles.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.users.user_id IS 'Identificador único del usuario';
COMMENT ON COLUMN ff_medic_db.users.role_id IS 'Identificador del rol asignado';
COMMENT ON COLUMN ff_medic_db.users.name IS 'Nombre del usuario';
COMMENT ON COLUMN ff_medic_db.users.paternal_surname IS 'Apellido paterno del usuario';
COMMENT ON COLUMN ff_medic_db.users.maternal_surname IS 'Apellido materno del usuario';
COMMENT ON COLUMN ff_medic_db.users.cmp_code IS 'Código del Colegio Médico del Perú';
COMMENT ON COLUMN ff_medic_db.users.username IS 'Nombre de usuario para inicio de sesión';
COMMENT ON COLUMN ff_medic_db.users.password IS 'Contraseña hasheada del usuario';
COMMENT ON COLUMN ff_medic_db.users.email IS 'Correo electrónico del usuario';
COMMENT ON COLUMN ff_medic_db.users.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.users.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.users.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.services.service_id IS 'Identificador único del servicio';
COMMENT ON COLUMN ff_medic_db.services.name IS 'Nombre del servicio';
COMMENT ON COLUMN ff_medic_db.services.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.diagnoses.diagnosis_id IS 'Identificador único del diagnóstico';
COMMENT ON COLUMN ff_medic_db.diagnoses.cie_10 IS 'Código CIE-10 del diagnóstico';
COMMENT ON COLUMN ff_medic_db.diagnoses.description IS 'Descripción del diagnóstico';
COMMENT ON COLUMN ff_medic_db.diagnoses.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.active_ingredients.active_ingredient_id IS 'Identificador único del principio activo';
COMMENT ON COLUMN ff_medic_db.active_ingredients.name IS 'Nombre del principio activo';
COMMENT ON COLUMN ff_medic_db.active_ingredients.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.manufacturers.manufacturer_id IS 'Identificador único del fabricante';
COMMENT ON COLUMN ff_medic_db.manufacturers.name IS 'Nombre del fabricante';
COMMENT ON COLUMN ff_medic_db.manufacturers.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.dosage_forms.dosage_form_id IS 'Identificador único de la forma farmacéutica';
COMMENT ON COLUMN ff_medic_db.dosage_forms.name IS 'Nombre de la forma farmacéutica';
COMMENT ON COLUMN ff_medic_db.dosage_forms.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.medicaments.medicament_id IS 'Identificador único del medicamento';
COMMENT ON COLUMN ff_medic_db.medicaments.name IS 'Nombre comercial del medicamento';
COMMENT ON COLUMN ff_medic_db.medicaments.manufacturer_id IS 'Identificador del fabricante asociado';
COMMENT ON COLUMN ff_medic_db.medicaments.concentration IS 'Concentración del principio activo';
COMMENT ON COLUMN ff_medic_db.medicaments.dosage_form_id IS 'Identificador de la forma farmacéutica asociada';
COMMENT ON COLUMN ff_medic_db.medicaments.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.medicaments_ingredients.medicament_id IS 'Identificador del medicamento asociado';
COMMENT ON COLUMN ff_medic_db.medicaments_ingredients.active_ingredient_id IS 'Identificador del principio activo asociado';
COMMENT ON COLUMN ff_medic_db.attentions.attention_id IS 'Identificador único de la atención médica';
COMMENT ON COLUMN ff_medic_db.attentions.patient_id IS 'Identificador del paciente atendido';
COMMENT ON COLUMN ff_medic_db.attentions.service_id IS 'Identificador del servicio brindado';
COMMENT ON COLUMN ff_medic_db.attentions.illness_duration IS 'Tiempo de enfermedad del paciente';
COMMENT ON COLUMN ff_medic_db.attentions.onset_type IS 'Tipo de inicio de la enfermedad';
COMMENT ON COLUMN ff_medic_db.attentions.course IS 'Curso de la enfermedad';
COMMENT ON COLUMN ff_medic_db.attentions.current_disease IS 'Descripción de la enfermedad actual';
COMMENT ON COLUMN ff_medic_db.attentions.work_plan IS 'Plan de trabajo del paciente';
COMMENT ON COLUMN ff_medic_db.attentions.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.attentions.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.attention_diagnoses.attention_diagnosis_id IS 'Identificador único del diagnóstico asociado';
COMMENT ON COLUMN ff_medic_db.attention_diagnoses.attention_id IS 'Identificador de la atención asociada';
COMMENT ON COLUMN ff_medic_db.attention_diagnoses.diagnosis_id IS 'Identificador del diagnóstico asignado';
COMMENT ON COLUMN ff_medic_db.attention_diagnoses.type IS 'Tipo de diagnóstico';
COMMENT ON COLUMN ff_medic_db.attention_diagnoses.specifications IS 'Especificaciones del diagnóstico';
COMMENT ON COLUMN ff_medic_db.attention_diagnoses.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.attention_diagnoses.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.signs_symptoms.sign_symptom_id IS 'Identificador único del signo o síntoma';
COMMENT ON COLUMN ff_medic_db.signs_symptoms.attention_id IS 'Identificador de la atención asociada';
COMMENT ON COLUMN ff_medic_db.signs_symptoms.diagnosis_id IS 'Identificador del diagnóstico asociado';
COMMENT ON COLUMN ff_medic_db.signs_symptoms.observations IS 'Observaciones del signo o síntoma';
COMMENT ON COLUMN ff_medic_db.signs_symptoms.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.signs_symptoms.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.health_metrics.health_metric_id IS 'Identificador único de las métricas de salud';
COMMENT ON COLUMN ff_medic_db.health_metrics.attention_id IS 'Identificador de la atención asociada';
COMMENT ON COLUMN ff_medic_db.health_metrics.temperature IS 'Temperatura corporal del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.spo2 IS 'Saturación de oxígeno del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.heart_rate IS 'Frecuencia cardíaca del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.respiratory_rate IS 'Frecuencia respiratoria del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.systolic_bp IS 'Presión arterial sistólica del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.diastolic_bp IS 'Presión arterial diastólica del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.hgt IS 'Hemoglucotest del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.hemoglobin IS 'Hemoglobina del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.weight IS 'Peso corporal del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.abdominal_perimeter IS 'Perímetro abdominal del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.height IS 'Talla del paciente';
COMMENT ON COLUMN ff_medic_db.health_metrics.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.health_metrics.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.bio_functions.bio_function_id IS 'Identificador único de la función biológica';
COMMENT ON COLUMN ff_medic_db.bio_functions.attention_id IS 'Identificador de la atención asociada';
COMMENT ON COLUMN ff_medic_db.bio_functions.type IS 'Tipo de función biológica evaluada';
COMMENT ON COLUMN ff_medic_db.bio_functions.status IS 'Estado de la función biológica';
COMMENT ON COLUMN ff_medic_db.bio_functions.observations IS 'Observaciones de la función biológica';
COMMENT ON COLUMN ff_medic_db.bio_functions.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.bio_functions.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.physical_exams.physical_exam_id IS 'Identificador único del sistema evaluado';
COMMENT ON COLUMN ff_medic_db.physical_exams.attention_id IS 'Identificador de la atención asociada';
COMMENT ON COLUMN ff_medic_db.physical_exams.system IS 'Sistema del cuerpo evaluado';
COMMENT ON COLUMN ff_medic_db.physical_exams.status IS 'Estado del sistema evaluado';
COMMENT ON COLUMN ff_medic_db.physical_exams.observations IS 'Observaciones del examen físico';
COMMENT ON COLUMN ff_medic_db.physical_exams.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.physical_exams.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.exams.exam_id IS 'Identificador único de la orden de examen';
COMMENT ON COLUMN ff_medic_db.exams.attention_id IS 'Identificador de la atención asociada';
COMMENT ON COLUMN ff_medic_db.exams.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.exams.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.exam_types.exam_type_id IS 'Identificador único del tipo de examen';
COMMENT ON COLUMN ff_medic_db.exam_types.description IS 'Descripción del tipo de examen';
COMMENT ON COLUMN ff_medic_db.exam_types.is_active IS 'Estado del registro';
COMMENT ON COLUMN ff_medic_db.exam_items.exam_item_id IS 'Identificador único del ítem de examen';
COMMENT ON COLUMN ff_medic_db.exam_items.exam_id IS 'Identificador de la orden de examen asociada';
COMMENT ON COLUMN ff_medic_db.exam_items.exam_type_id IS 'Identificador del tipo de examen solicitado';
COMMENT ON COLUMN ff_medic_db.exam_items.indications IS 'Indicaciones para la realización del examen';
COMMENT ON COLUMN ff_medic_db.exam_items.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.prescriptions.prescription_id IS 'Identificador único de la receta';
COMMENT ON COLUMN ff_medic_db.prescriptions.attention_id IS 'Identificador de la atención asociada';
COMMENT ON COLUMN ff_medic_db.prescriptions.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.prescriptions.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.prescription_items.prescription_item_id IS 'Identificador único del medicamento recetado';
COMMENT ON COLUMN ff_medic_db.prescription_items.prescription_id IS 'Identificador de la receta asociada';
COMMENT ON COLUMN ff_medic_db.prescription_items.medicament_id IS 'Identificador del medicamento recetado';
COMMENT ON COLUMN ff_medic_db.prescription_items.quantity IS 'Cantidad recetada del medicamento';
COMMENT ON COLUMN ff_medic_db.prescription_items.indications IS 'Indicaciones de uso del medicamento';
COMMENT ON COLUMN ff_medic_db.prescription_items.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.prescription_items.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.prescription_diagnoses.prescription_item_id IS 'Identificador del medicamento recetado';
COMMENT ON COLUMN ff_medic_db.prescription_diagnoses.attention_diagnosis_id IS 'Identificador del diagnóstico asociado';
COMMENT ON COLUMN ff_medic_db.referrals.referral_id IS 'Identificador único de la interconsulta';
COMMENT ON COLUMN ff_medic_db.referrals.attention_id IS 'Identificador de la atención asociada';
COMMENT ON COLUMN ff_medic_db.referrals.service_id IS 'Identificador del servicio de destino';
COMMENT ON COLUMN ff_medic_db.referrals.diagnosis_id IS 'Identificador del diagnóstico asociado';
COMMENT ON COLUMN ff_medic_db.referrals.reason IS 'Motivo de la interconsulta';
COMMENT ON COLUMN ff_medic_db.referrals.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.referrals.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.clinical_histories.clinical_history_id IS 'Identificador único del antecedente clínico';
COMMENT ON COLUMN ff_medic_db.clinical_histories.patient_id IS 'Identificador del paciente asociado';
COMMENT ON COLUMN ff_medic_db.clinical_histories.diagnosis_id IS 'Identificador del diagnóstico asociado';
COMMENT ON COLUMN ff_medic_db.clinical_histories.type IS 'Tipo de antecedente';
COMMENT ON COLUMN ff_medic_db.clinical_histories.specifications IS 'Especificaciones del antecedente';
COMMENT ON COLUMN ff_medic_db.clinical_histories.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.clinical_histories.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.family_histories.family_history_id IS 'Identificador único del antecedente familiar';
COMMENT ON COLUMN ff_medic_db.family_histories.patient_id IS 'Identificador del paciente asociado';
COMMENT ON COLUMN ff_medic_db.family_histories.type IS 'Tipo de familiar';
COMMENT ON COLUMN ff_medic_db.family_histories.status IS 'Estado del familiar';
COMMENT ON COLUMN ff_medic_db.family_histories.specifications IS 'Especificaciones del antecedente familiar';
COMMENT ON COLUMN ff_medic_db.family_histories.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.family_histories.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.gynecological_history_id IS 'Identificador único del antecedente ginecológico';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.patient_id IS 'Identificador del paciente asociado';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.menarche IS 'Edad de la menarquia del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.menstrual_cycle IS 'Tipo de ciclo menstrual del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.last_menstrual_period IS 'Fecha de la última menstruación del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.contraceptive_method IS 'Método anticonceptivo del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.gestations IS 'Número de gestaciones del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.parity IS 'Número de partos del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.orientation IS 'Orientación sexual del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.andria IS 'Número de abortos del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.isa IS 'Inicio de Actividad Sexual del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.lsa IS 'Última Actividad Sexual del paciente';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.gynecological_histories.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.allergy_histories.allergy_history_id IS 'Identificador único del antecedente alérgico';
COMMENT ON COLUMN ff_medic_db.allergy_histories.patient_id IS 'Identificador del paciente asociado';
COMMENT ON COLUMN ff_medic_db.allergy_histories.diagnosis_id IS 'Identificador del diagnóstico asociado';
COMMENT ON COLUMN ff_medic_db.allergy_histories.specifications IS 'Especificaciones de la alergia';
COMMENT ON COLUMN ff_medic_db.allergy_histories.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.allergy_histories.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.ram_histories.ram_history_id IS 'Identificador único de la RAM';
COMMENT ON COLUMN ff_medic_db.ram_histories.patient_id IS 'Identificador del paciente asociado';
COMMENT ON COLUMN ff_medic_db.ram_histories.active_ingredient_id IS 'Identificador del principio activo asociado';
COMMENT ON COLUMN ff_medic_db.ram_histories.diagnosis_id IS 'Identificador del diagnóstico asociado';
COMMENT ON COLUMN ff_medic_db.ram_histories.specifications IS 'Especificaciones de la reacción adversa';
COMMENT ON COLUMN ff_medic_db.ram_histories.created_at IS 'Fecha de creación del registro';
COMMENT ON COLUMN ff_medic_db.ram_histories.updated_at IS 'Fecha de actualización del registro';
COMMENT ON COLUMN ff_medic_db.audits.audit_id IS 'Identificador único de la auditoría';
COMMENT ON COLUMN ff_medic_db.audits.table_name IS 'Nombre de la tabla afectada';
COMMENT ON COLUMN ff_medic_db.audits.record_id IS 'Identificador del registro afectado';
COMMENT ON COLUMN ff_medic_db.audits.action IS 'Tipo de acción realizada';
COMMENT ON COLUMN ff_medic_db.audits.user_id IS 'Identificador del usuario que realizó la acción';
COMMENT ON COLUMN ff_medic_db.audits.old_data IS 'Datos anteriores a la modificación';
COMMENT ON COLUMN ff_medic_db.audits.new_data IS 'Datos posteriores a la modificación';
COMMENT ON COLUMN ff_medic_db.audits.ip IS 'Dirección IP de la solicitud';
COMMENT ON COLUMN ff_medic_db.audits.user_agent IS 'Aplicación origen de la solicitud';
COMMENT ON COLUMN ff_medic_db.audits.created_at IS 'Fecha de creación del registro';

-- Agregar comentarios a indices
COMMENT ON INDEX ff_medic_db.idx_patients_document_number IS 'Búsqueda de paciente por número de documento';
COMMENT ON INDEX ff_medic_db.idx_attentions_created_at IS 'Filtro de atenciones por fecha';
COMMENT ON INDEX ff_medic_db.idx_attentions_patient_id IS 'Atenciones de un paciente';
COMMENT ON INDEX ff_medic_db.idx_clinical_histories_patient_id IS 'Antecedentes clínicos por paciente';
COMMENT ON INDEX ff_medic_db.idx_family_histories_patient_id IS 'Antecedentes familiares por paciente';
COMMENT ON INDEX ff_medic_db.idx_allergy_histories_patient_id IS 'Antecedentes alérgicos por paciente';
COMMENT ON INDEX ff_medic_db.idx_ram_histories_patient_id IS 'RAM por paciente';
COMMENT ON INDEX ff_medic_db.idx_attention_diagnoses_attention_id IS 'Diagnósticos de una atención';
COMMENT ON INDEX ff_medic_db.idx_signs_symptoms_attention_id IS 'Signos y síntomas de una atención';
COMMENT ON INDEX ff_medic_db.idx_bio_functions_attention_id IS 'Funciones biológicas de una atención';
COMMENT ON INDEX ff_medic_db.idx_physical_exams_attention_id IS 'Exámenes físicos de una atención';
COMMENT ON INDEX ff_medic_db.idx_exams_attention_id IS 'Órdenes de examen de una atención';
COMMENT ON INDEX ff_medic_db.idx_prescriptions_attention_id IS 'Recetas de una atención';
COMMENT ON INDEX ff_medic_db.idx_referrals_attention_id IS 'Interconsultas de una atención';
COMMENT ON INDEX ff_medic_db.idx_users_role_id IS 'Usuarios por rol';
COMMENT ON INDEX ff_medic_db.idx_medicaments_manufacturer_id IS 'Medicamentos por fabricante';
COMMENT ON INDEX ff_medic_db.idx_medicaments_dosage_form_id IS 'Medicamentos por forma farmacéutica';
COMMENT ON INDEX ff_medic_db.idx_exam_items_exam_id IS 'Ítems de una orden de examen';
COMMENT ON INDEX ff_medic_db.idx_exam_items_exam_type_id IS 'Ítems por tipo de examen';
COMMENT ON INDEX ff_medic_db.idx_prescription_items_prescription_id IS 'Ítems de una receta';
COMMENT ON INDEX ff_medic_db.idx_referrals_service_id IS 'Interconsultas por servicio de destino';
COMMENT ON INDEX ff_medic_db.idx_attention_diagnoses_diagnosis_id IS 'Atenciones por diagnóstico';
COMMENT ON INDEX ff_medic_db.idx_signs_symptoms_diagnosis_id IS 'Signos y síntomas por diagnóstico';
COMMENT ON INDEX ff_medic_db.idx_referrals_diagnosis_id IS 'Interconsultas por diagnóstico';
